version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm@5"
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Lint tests
          command: npm run lint
      - run:
          name: Snapshot tests
          env:
            REACT_APP_FIREBASE_API_KEY: $REACT_APP_FIREBASE_API_KEY
            REACT_APP_FIREBASE_PROJECT_ID: $REACT_APP_FIREBASE_PROJECT_ID
            REACT_APP_FIREBASE_MESSAGING_SENDER_ID: $REACT_APP_FIREBASE_MESSAGING_SENDER_ID
            REACT_APP_FIREBASE_APP_ID: $REACT_APP_FIREBASE_APP_ID
            REACT_APP_FIREBASE_MEASUREMENTID: $REACT_APP_FIREBASE_MEASUREMENTID
            REACT_APP_FIREBASE_FCM_VAPID_KEY: $REACT_APP_FIREBASE_FCM_VAPID_KEY
            REACT_APP_AUTH_DOMAIN: $REACT_APP_AUTH_DOMAIN
          command: npm run test
